### ISSUE TITLE
package(.preload) problem with lanes > 3.10.1

### ISSUE THREAD

**Issue by terminar** [LuaLanes/lanes#142]
Hi, 
I am using lua-amalg to amalgamate some modules within one Lua script, that's where I got into trouble (PUC Lua 5.3.4)

1. using lanes > 3.10.1, the 'preload_require' and the 'require' call will fail. The lane function can't find the "core.lanemain" preloaded code. The package.preload.* and package.loaded.* tables seem to be empty. I also tried to pass it through { packages = packages } via .configure() but that also doesn't work
2. using lanes 3.10.1, the example code is working - but only with the 'preload_require' call. The 'require' is failing.

I'll stick with lanes 3.10.1 with the preload_require function but I want to understand, what I have done wrong.

```lua
#!/usr/bin/env lua

package.preload["core.lanemain"] = load([[
    _M = {}
    function _M.run()
        print("run")
        local i=5
        while i > 0 do 
            print("cnt: ",i)
            os.execute("sleep 1")
            i=i-1
        end
    end
    return _M
]])

print("Initializing lanes")
local lanes = require "lanes"
lanes.configure()

local function preload_require(module,...)
    if not package.loaded[module] and package.preload and package.preload[module] then
        package.loaded[module] = package.preload[module](module,...)
    end
    return package.loaded[module]
end

print("Start")
local lanegen = lanes.gen("*",
    function()
        print("lane start, require lanemain")
        local lanemain

        -- will fail: reports > no field package.preload['core.lanemain']...
        local stat, err = pcall(function()
            lanemain = require 'core.lanemain'
        end)
        if not lanemain or err then print("require 'core.lanemain' failed") end
        
        lanemain  = preload_require 'core.lanemain'
        if lanemain then print("preload_require 'core.lanemain' successful") end

        lanemain.run()

    end)

local lane_handle = lanegen()

local res, err = lane_handle:join()
if not res and err then
    print("Lane error: ", err)
end
```

**Comment by benoit-germain** [comment]
I think that there is an error in the documentation (as in, Lanes doesn't behave as the documentation states), right here, about the .package option in the Lanes generation options table:
"If not specified, the created lane will receive the current values of package. Only path, cpath, preload and loaders (Lua 5.1)/searchers (Lua 5.2) are transfered."

In fact, what happens in practice when the package option is not specified, is that the lane body uses whatever is present in the Lane's state package.preload (package.path and package.cpath are copied over though).

To make the behavior consistent I can just force cloning the package.preload table, but that won't help you if you don't upgrade to a more recent version of Lanes. I'd say you'll have to use ```on_state_create```:
```lua
local core_lane_main = load([[
    local _M = {}
    function _M.run()
        print("run")
        local i=5
        while i > 0 do 
            print("cnt: ",i)
            os.execute("sleep 1")
            i=i-1
        end
    end
    return _M
]])

package.preload["core.lanemain"] = core_lane_main

print("Initializing lanes")
local lanes = require "lanes"
lanes.configure{
    with_timers=true,
    on_state_create = function()
        package.preload["core.lanemain"] = core_lane_main
    end
}

local function preload_require(module,...)
    print( "entering preload_require for " .. module, package.loaded[module], package.preload, package.preload[module])
    if not package.loaded[module] and package.preload and package.preload[module] then
        print( "preload_require: using package.preload[" .. module .. "]")
        package.loaded[module] = package.preload[module](module,...)
    end
    print( "exiting preload_require -> " .. type( package.loaded[module]))
    return package.loaded[module]
end

print("Before lane start, list package.preload")
for k,v in pairs( package.preload) do
    print( k, v)
end

print("Start")
local lanegen = lanes.gen("*",
    function()
        local lanes = require "lanes"
        set_finalizer( function( err, stk)
            if err == lanes.cancel_error then
                -- lane cancellation is performed by throwing a special userdata as error
                print( "after cancel")
            elseif err then
                -- no special error: true error
                print( " error: "..tostring(err))
            else
                -- no error: we just got finalized
                print( "done")
            end
        end)

        print("lane start, list package.preload")
        for k,v in pairs( package.preload) do
            print( k, v)
        end

        print("lane start, require lanemain")
        local lanemain

        -- will fail: reports > no field package.preload['core.lanemain']...
        local stat, err = pcall(function()
            lanemain = require 'core.lanemain'
        end)
        if not lanemain or err then print("require 'core.lanemain' failed because " .. err) end
        
        lanemain  = preload_require 'core.lanemain'
        if lanemain then print("preload_require 'core.lanemain' successful") end

        lanemain.run()

    end)

local lane_handle = lanegen()

local res, err = lane_handle:join()
if not res and err then
    print("Lane error: ", err)
end
```

**Comment by terminar** [comment]
Awesome, I tried it with my current code, it's working! Thank you very much! :)

> To make the behavior consistent I can just force cloning the package.preload table, but that won't help you if you don't upgrade to a more recent version of Lanes. I'd say you'll have to use `on_state_create`:

Yes, also for other lane-users to have package.preload cloned will be maybe helpful. 
I'm back on the bleeding edge git version now, meaning: upgrade isn't a problem anymore.

A last problem which I don't understand is the following code and error message (even if I am highjacking this issue a little bit):

```Lua
local log = require 'mylog'("OTHER")
local GLib = require("lgi").GLib
local GVariant = GLib.Variant

function genMyLane()
    local lanegen = lanes.gen("*",
    function()
        log.debug("test")
        local gv = GVariant("b",true)
    end)

    local lane_handle = lanegen()
    local res, err = lane_handle:join()
    if not res and err then
        print("Lane error: ", err)
    end
end

genMyLane()
```

When I try this code (using mylog which is a lua module which itself uses a Lua C-Module named mylog.core), i'll get these error messages (each time I execute the code, I'll get a different missing method):

```Lua
lua: /usr/share/lua/5.3/lanes.lua:330: main: function 'package/loaded/mylog/level_tostring' not found in Lane #0x6e5c18 destination transfer database.
lua: /usr/share/lua/5.3/lanes.lua:330: main: function 'package/loaded/mylog/category_tostring' not found in Lane #0x6e5b48 destination transfer database.
lua: /usr/share/lua/5.3/lanes.lua:330: main: function 'package/loaded/mylog.core/log' not found in Lane #0x6e3dd8 destination transfer database.
```

Even if I try to copy "package.loaded" in "on_state_create", I'll get more confusing errors:
```Lua
lua: /usr/share/lua/5.3/lanes.lua:330: main: function 'lanes.core/set_thread_priority' not found in main destination transfer database.
lua: /usr/share/lua/5.3/lanes.lua:330: main: function 'package/searchpath' not found in main destination transfer database.
lua: /usr/share/lua/5.3/lanes.lua:330: main: function 'string/match' not found in main destination 
lua: /usr/share/lua/5.3/lanes.lua:330: main: function 'bit32/extract' not found in main destination transfer database.
lua: /usr/share/lua/5.3/lanes.lua:330: main: function 'debug/gethook' not found in main destination transfer database.
lua: /usr/share/lua/5.3/lanes.lua:330: main: function 'coroutine/isyieldable' not found in main destination transfer database.
lua: /usr/share/lua/5.3/lanes.lua:330: main: function 'lanes.core/lane_new' not found in main 
lua: /usr/share/lua/5.3/lanes.lua:330: main: function 'rawget' not found in main destination transfer ```

When I remove the "log.debug" line (or move the require 'mylog' into the lanes function) and only try to use the GVariant from LGI, I'll get

```Lua
lua: /usr/share/lua/5.3/lanes.lua:330: can't copy non-deep full userdata across lanes
```
OK, I've read about it in the lanes documentation but I haven't understand it yet.
working if I put the whole 
```Lua
local GLib = require("lgi").GLib
local GVariant = GLib.Variant
```
block into the lanes function but that means, I have to put a bunch of require's into every lane function I'll use. That will make the code filled with much boilerplate code.

Is there any way to have the require on a central part / local / function / something which can be reused in the lanes function?

**Comment by benoit-germain** [comment]
untested code that should do what you want
```lua
local genericLane = function( fun_, ...)
    return fun( ...)
end

local g = lanes.gen( { required = { "OTHER", "lgi"}}, genericLane)

h1 = g( foo, ...)
h2 = g( bar, ...)
h3 = g( baz, ...)
```

**Comment by terminar** [comment]
Using 'required' greets me with a segfault, I have stopped trying that direction.

But I found a way to use something like "shared code" with a simple "hack". Maybe someone is interested, so here is a code snipplet.

```Lua
local preloaded = package.preload
require 'lanes'.configure{
    with_timers=true,
    on_state_create = function()
        for k,v in pairs(preloaded) do
            package.preload[k] = v
        end
    end
}

package.preload["module.name.shared"] = function()
    local _ENV = setmetatable({}, {__index = _G}) 
   
    log = require 'mylog'("OTHER")

    function someFancyFunction()
        print("do something")
        log.debug("debug something")
    end
    ...

    return _ENV
end

lanes.gen("*",function()
    local _ENV = require 'module.name.shared'
    log.debug("test")
    someFancyFunction()
    ...
end)()

lanes.gen("*",function()
    local _ENV = require 'module.name.shared'
    log.debug("second test")
    ...
end)()
```

Using your previous tip with on_state_create which copies the package.preload table, I can reach my "shared" code function and use it as environment. I tested it for the last two hours, it seems to be stable, doesn't crash. It is maybe not the best solution to my problem but it works well and looks readable. The boilerplate code is gone and I can put the "shared" code into another module without dealing with lanes.

Thanks you!

**Comment by benoit-germain** [comment]
Do you know if that segfault in inside lanes itself? If so I can probably do something about it, but I need to be able to reproduce it.

**Comment by terminar** [comment]
I think it's due to lanes but not in the lanes code itself.

lanes.gen is working as expected (meaning, it doesn't crash) but if I try to call the returned function, a segfault will occur. Below you can see a backtrace.

Btw, I only have to add required = { 'lgi', ... } to the opts of lanes.gen and the segfault will occur, it is not important that the required libs are used within the generated lanes function.
That even happens if I am adding an empty table like ```required = {}```. As long as required is found in the opts, it will crash.

Maybe you can find some information from the gdb backtrace.
```
#0  __GI_raise (sig=sig@entry=6) at /usr/src/debug/glibc/2.27-r0/git/sysdeps/unix/sysv/linux/raise.c:51
#1  0x000000338b035461 in __GI_abort () at /usr/src/debug/glibc/2.27-r0/git/stdlib/abort.c:79
#2  0x00000000004080d2 in luaD_throw (L=0x7984a8, errcode=<optimized out>) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:130
#3  0x0000000000407b8d in luaG_errormsg (L=L@entry=0x7984a8) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldebug.c:648
#4  0x0000000000407cab in luaG_runerror (L=L@entry=0x7984a8, fmt=fmt@entry=0x42663f "attempt to %s a %s value%s")
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldebug.c:661
#5  0x0000000000407cf0 in luaG_typeerror (L=0x7984a8, o=0x798ad0, op=0x428846 "index")
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldebug.c:587
#6  0x0000000000412b4a in luaV_finishget (L=0x7984a8, t=0x798ad0, key=0x798ae0, val=0x798ae0, slot=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lvm.c:169
#7  0x0000000000404f6a in auxgetstr (L=L@entry=0x7984a8, t=0x798ad0, k=k@entry=0x7f0f1e330823 "on_state_create")
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lapi.c:597
#8  0x0000000000405d41 in lua_getfield (L=L@entry=0x7984a8, idx=idx@entry=-1, k=k@entry=0x7f0f1e330823 "on_state_create")
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lapi.c:623
#9  0x00007f0f1e32bfe5 in call_on_state_create (U=0x6ab368, L=0x7984a8, from_=0x765a98, mode_=eLM_LaneBody)
    at /usr/src/debug/lanes/3.10.1-r0/git/src/tools.c:589
#10 0x00007f0f1e32ca0d in luaG_newstate (U=U@entry=0x6ab368, from_=from_@entry=0x765a98, libs_=<optimized out>, libs_@entry=0x0)
    at /usr/src/debug/lanes/3.10.1-r0/git/src/tools.c:708
#11 0x00007f0f1e323480 in LG_lane_new (L=0x765a98) at /usr/src/debug/lanes/3.10.1-r0/git/src/lanes.c:2207
#12 0x0000000000408b0e in luaD_precall (L=0x765a98, func=0x7861c0, nresults=-1)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:434
#13 0x0000000000413e94 in luaV_execute (L=0x765a98) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lvm.c:1149
#14 0x0000000000408ddf in luaD_call (L=0x765a98, func=<optimized out>, nResults=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:499
#15 0x000000000040665a in lua_pcallk (L=L@entry=0x765a98, nargs=<optimized out>, nresults=nresults@entry=-1,
    errfunc=errfunc@entry=0, ctx=ctx@entry=0, k=k@entry=0x41bde0 <finishpcall>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lapi.c:980
#16 0x000000000041be71 in luaB_pcall (L=0x765a98) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lbaselib.c:424
#17 0x0000000000408b0e in luaD_precall (L=0x765a98, func=0x786180, nresults=2) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:434
#18 0x0000000000413c0d in luaV_execute (L=0x765a98) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lvm.c:1134
#19 0x0000000000408ddf in luaD_call (L=0x765a98, func=<optimized out>, nResults=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:499
#20 0x000000000040665a in lua_pcallk (L=L@entry=0x765a98, nargs=<optimized out>, nresults=nresults@entry=-1,
    errfunc=errfunc@entry=0, ctx=ctx@entry=0, k=k@entry=0x41bde0 <finishpcall>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lapi.c:980
#21 0x000000000041be71 in luaB_pcall (L=0x765a98) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lbaselib.c:424
#22 0x0000000000408b0e in luaD_precall (L=0x765a98, func=0x786110, nresults=2) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:434
#23 0x0000000000413c0d in luaV_execute (L=0x765a98) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lvm.c:1134
#24 0x000000000040827f in luaD_rawrunprotected (L=L@entry=0x765a98, f=f@entry=0x408ce0 <resume>, ud=ud@entry=0x7ffd8342cd4c)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:142
#25 0x0000000000408f21 in lua_resume (L=L@entry=0x765a98, from=from@entry=0x636268, nargs=<optimized out>, nargs@entry=1)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:664
#26 0x000000000041c527 in auxresume (L=L@entry=0x636268, co=co@entry=0x765a98, narg=1)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lcorolib.c:39
#27 0x000000000041c867 in luaB_coresume (L=0x636268) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lcorolib.c:60
#28 0x0000000000408b0e in luaD_precall (L=0x636268, func=0x721eb0, nresults=0) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:434
#29 0x0000000000413c0d in luaV_execute (L=0x636268) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lvm.c:1134
#30 0x0000000000408ddf in luaD_call (L=L@entry=0x636268, func=<optimized out>, nResults=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:499
#31 0x0000000000408e31 in luaD_callnoyield (L=0x636268, func=<optimized out>, nResults=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:509
#32 0x000000000040827f in luaD_rawrunprotected (L=L@entry=0x636268, f=0x405090 <f_call>, ud=0x7ffd8342d040)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:142
#33 0x000000000040911b in luaD_pcall (L=0x636268, func=<optimized out>, u=<optimized out>, old_top=304, ef=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:729
#34 0x00000000004065d6 in lua_pcallk (L=L@entry=0x636268, nargs=nargs@entry=0, nresults=nresults@entry=0, errfunc=errfunc@entry=1,
    ctx=ctx@entry=0, k=k@entry=0x0) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lapi.c:968
#35 0x00007f0f1e545377 in luv_call_callback (L=0x636268, data=<optimized out>, id=<optimized out>, nargs=0)
    at /usr/src/debug/luv/1.22.0+gitAUTOINC+5dad5f445d-r0/git/src/lhandle.c:133
#36 0x00007f0f1e556808 in uv__run_timers (loop=loop@entry=0x68c8f8)
    at /usr/src/debug/luv/1.22.0+gitAUTOINC+5dad5f445d-r0/git/deps/libuv/src/timer.c:174
#37 0x00007f0f1e55a942 in uv_run (loop=0x68c8f8, mode=mode@entry=UV_RUN_DEFAULT)
    at /usr/src/debug/luv/1.22.0+gitAUTOINC+5dad5f445d-r0/git/deps/libuv/src/unix/core.c:361
#38 0x00007f0f1e5531e5 in luv_run (L=0x636268) at /usr/src/debug/luv/1.22.0+gitAUTOINC+5dad5f445d-r0/git/src/loop.c:33
#39 0x0000000000408b0e in luaD_precall (L=0x636268, func=0x721e30, nresults=-1)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:434
#40 0x0000000000413e94 in luaV_execute (L=0x636268) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lvm.c:1149
#41 0x0000000000408ddf in luaD_call (L=L@entry=0x636268, func=<optimized out>, nResults=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:499
#42 0x0000000000408e31 in luaD_callnoyield (L=0x636268, func=<optimized out>, nResults=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:509
#43 0x000000000040827f in luaD_rawrunprotected (L=L@entry=0x636268, f=0x405090 <f_call>, ud=0x7ffd8342d3b0)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:142
#44 0x000000000040911b in luaD_pcall (L=0x636268, func=<optimized out>, u=<optimized out>, old_top=240, ef=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:729
#45 0x00000000004065d6 in lua_pcallk (L=L@entry=0x636268, nargs=<optimized out>, nresults=nresults@entry=-1,
    errfunc=errfunc@entry=0, ctx=ctx@entry=0, k=k@entry=0x41bde0 <finishpcall>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lapi.c:968
#46 0x000000000041be71 in luaB_pcall (L=0x636268) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lbaselib.c:424
#47 0x0000000000408b0e in luaD_precall (L=0x636268, func=0x721df0, nresults=2) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:434
#48 0x0000000000413c0d in luaV_execute (L=0x636268) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lvm.c:1134
#49 0x0000000000408ddf in luaD_call (L=L@entry=0x636268, func=<optimized out>, nResults=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:499
#50 0x0000000000408e31 in luaD_callnoyield (L=0x636268, func=<optimized out>, nResults=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:509
#51 0x000000000040827f in luaD_rawrunprotected (L=L@entry=0x636268, f=0x405090 <f_call>, ud=0x7ffd8342d660)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:142
#52 0x000000000040911b in luaD_pcall (L=0x636268, func=<optimized out>, u=<optimized out>, old_top=80, ef=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:729
#53 0x00000000004065d6 in lua_pcallk (L=L@entry=0x636268, nargs=nargs@entry=0, nresults=nresults@entry=-1, errfunc=errfunc@entry=3,
    ctx=ctx@entry=0, k=k@entry=0x0) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lapi.c:968
#54 0x00000000004040db in docall (L=L@entry=0x636268, narg=narg@entry=0, nres=nres@entry=-1)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lua.c:205
#55 0x0000000000404db7 in handle_script (argv=<optimized out>, L=0x636268) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lua.c:445
#56 pmain (L=0x636268) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lua.c:580
#57 0x0000000000408b0e in luaD_precall (L=L@entry=0x636268, func=0x636890, nresults=1)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:434
#58 0x0000000000408dd3 in luaD_call (L=L@entry=0x636268, func=<optimized out>, nResults=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:498
#59 0x0000000000408e31 in luaD_callnoyield (L=0x636268, func=<optimized out>, nResults=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:509
#60 0x000000000040827f in luaD_rawrunprotected (L=L@entry=0x636268, f=0x405090 <f_call>, ud=0x7ffd8342d8f0)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:142
#61 0x000000000040911b in luaD_pcall (L=0x636268, func=<optimized out>, u=<optimized out>, old_top=16, ef=<optimized out>)
    at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/ldo.c:729
#62 0x00000000004065d6 in lua_pcallk (L=L@entry=0x636268, nargs=nargs@entry=2, nresults=nresults@entry=1, errfunc=errfunc@entry=0,
    ctx=ctx@entry=0, k=k@entry=0x0) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lapi.c:968
#63 0x0000000000403edb in main (argc=2, argv=0x7ffd8342da18) at /usr/src/debug/lua/5.3.4-r0/lua-5.3.4/src/lua.c:606
```
